version: '2'
services:
  cow-client:
    image: ${cow_image}
    environment:
      ALLOWEDCLIENT: ${ALLOWEDCLIENT}
      LISTEN: ${LISTEN}
      PROXY: ${PROXY}
    stdin_open: true
    volumes:
    - cow:/cow/.cow
    tty: true
    ports:
    - 7777:7777/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: cow=true
