name: cow-server # 应用商店模板名称
description: |
  # 应用商店模板描述
  cow：仅浏览器使用的VPN cow代理server端，需要再配合一个cow-client使用
version: 0.0.1 # 应用商店模板对应的版本
category: cow vpn # 用于模板搜索时的目录
maintainer: xianyuLuo # 该模板的维护者
license: GPL # 许可类型
